### ISSUE TITLE
Setup initial Spring Boot project

### ISSUE THREAD

**Issue by Colin23** [Colin23/java-todo-app#1]
# Initial Project Structure
This issue is about setting up the initial project structure.
> [!NOTE]
> This issue is still work in progress and may be updated at any time.

## ToDos for this issue

- [x] build.gradle.kts and Spring Boot setup
   - [x] Spring Boot Actuator
   - [x] SLF4J
   - [x] Extract the versioning tasks, class and method into their own file
   - [x] Finish configuring Spring Boot Actuator
   - [x] Setup Mockito?
   - [x] Include Google Checkstyles directly and own checkstyles indirectly over `build` task -> Google Checkstyles aren't great. I've set up my own in IntelliJ directly
   - [x] Add docker-compose dependency
   - [x] Add dependencies for PostgreSQL
   - [x] Evaluate necessity of Zipkin and add if needed -> Currently not needed
   - [x] Add testcontainer dependency and set it up
- [x] Initial REST endpoints (set a base endpoint url on the class)
   - [x] Post
   - [x] Put
   - [x] Get
   - [x] Delete 
- [x] An initial Test to check if everything works as expected
   - [x] Does not need any functionality. Just make sure the testing Framework works 
- [x] Perhaps some sort of RDBMS (ideally postgres)
   - [x] Some sort of ORM should be used. Maybe JDBC?
   - [x] Create some data manually and query with SQL to check if everything works
   - [x] Setup very basic CRUD method. This is just for testing, they will likely be deleted later 
   - [x] Make sure Docker Container starts
   - [x] Add a basic SQL Schema for the data 
- [x] Perhaps some sort of frontend (a JS frontend library)
   - [x] JS or TS?
   - [x] Angular, Vue, Svelte, Solid, React? 
   - [x] Setup some very basic HTML and CSS (Tailwind maybe?)
- [x] Fix Checkstyle errors
- [x] Add missing JavaDoc
